### ISSUE TITLE
File too big!

### ISSUE THREAD

**Issue by Jonskichov** [BSData/judge-dredd#19]
This data is causing an error when people try to download it. 

Google AppEngine log:

> com.google.appengine.api.urlfetch.ResponseTooLargeException: The response from url https://api.github.com/repos/BSData/judge-dredd/git/blobs/f465d743ac86fdd0f59dbd7a2bf404a708ead7c5 was too large.

Looks like the file is too big. So I had a look and it's **35Mb!** Any way this can be broken up into smaller files?

**Comment by Vescarea** [comment]
Hi yes im currently working on breaking it down starting with a single factions. would it be easier to make it one catalogue and game system per faction?

**Comment by Jonskichov** [comment]
@Vescarea 

Well the idea would be to have one game system, then multiple catalogues - one for each faction.

Assuming this is possible :S (I have never tried the game so no idea how it works!)

That said, remember that when you make a roster you can include multiple forces (for having a roster made up of multiple factions/catalogues) so you should be able to get that kind of thing working.

**Comment by Vescarea** [comment]
Ah i see I will get on that and make the necessary changes. It's similar to the set up with WH40 exept the forces would be a mix of heros and minions with some vehicles within each faction. So really it is just breaking it down.

Thanks
