### ISSUE TITLE
Do you need to do a Release?

### ISSUE THREAD

**Issue by Jonskichov** [BSData/judge-dredd#20]
Looks like a lot has changed!

But currently it has not been released to the public so no one is getting the changes yet.

There is a "release" button on the GitHub page where you can do this :)

Link: https://github.com/BSData/judge-dredd/releases

**Comment by Vescarea** [comment]
Ah thanks for the reminder been caught up with frostgrave, progressive campaigns and buying and selling are long work haha. Dredd files are in progress just working some new layouts.

**Comment by Jonskichov** [comment]
No problem! Just wanted to make sure you were aware of the release mechanism and/or you hadn't forgotten :) I see a lot of work has been done and I wanted to make sure the masses were able to access it.

I should pass on that I've had a few people say that they can't access the current Dredd files, and it's because the single catalogue file is so big that the appspot site is unable to handle it (hence me checking in).

I would suggest focussing on getting the main files into a basic working state (even without full rule/profile info) and then releasing incrementally. Don't wait for files to be "perfect", or for the whole lot to be complete before releasing. You can always release again in future, adding in rule/profile information and files for additional factions.

Recruiting some extra contributors to help authoring the files helps to spread the load too - don't feel like you have to do it all yourself!

If you need any advice, don't hesitate to drop me a line, or even drop a message into the 40k repo - those guys are really active.
