### ISSUE TITLE
Not working with BattleScribe 2

### ISSUE THREAD

**Issue by Deor** [BSData/judge-dredd#21]
Just tried to use these data files with Battlescribe 2.00.15 on my windows 10 PC and i dont get any forces listed. Ive attached a screenshot for you. tried a handful of different gangs and get the same type of issue.
![capture](https://cloud.githubusercontent.com/assets/1047936/24858797/ba6bc55a-1de5-11e7-9ddf-bfe43e2ab7e1.PNG)

**Comment by Vescarea** [comment]
Hello apologies for the long reply I had take time off and couldn't find anyone to fill in but I will get the basic units in for you there wont be any levelling up but that will come soon when I work out a reasonable methods.
