### ISSUE TITLE
[Anon] Bug report: Judge Dredd Redux.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/judge-dredd#22]
**File:** Judge Dredd Redux.gstz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I can create a force, but cannot any units to it, no units even apear. There's a red line with a " ! " above it, I click it,get a list of 6 errors:
"The Justice Department v1 (Justice dept 1 - Force/Gang) must spend 100000000pts more from 4 - inf. Robot Minion (minimum 100000000pts).
All errors are the same except the number after "...more from". The name of my test force is "Justice dept 1"

**Comment by Vescarea** [comment]
Hi there apologies but I hadn't gotten round to sorting it out yet heard a new version of the miniatures game was coming out but I will get the basic units up this weekend with their options.
