### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by skudfisher** [BSData/judge-dredd#24]
Since it hasn't been updated in a few years and there have been new releases I was wondering if I could update it with the new Block War expansion models. I've already got a 3rd of it completed locally with all the new characters for Characters_(WG2019).cat.

**Comment by Mad-Spy** [comment]
/invite

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/6756638810)
:robot: Invited @skudfisher with **push** access. Invite can be accepted on https://github.com/BSData/judge-dredd/invitations
